# Generated by Django 5.1.1 on 2024-09-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='эл.почта')),
                ('country', models.CharField(max_length=50, verbose_name='страна')),
                ('city', models.CharField(max_length=50, verbose_name='город')),
                ('street', models.CharField(max_length=50, verbose_name='улица')),
                ('number_bld', models.CharField(max_length=50, verbose_name='номер дома')),
                ('level', models.IntegerField(default=0, verbose_name='уровень')),
                ('company_type', models.CharField(choices=[('individual', 'ИП'), ('manufacture', 'завод'), ('retail', 'розница')], max_length=30, verbose_name='тип компании')),
                ('suppliers_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='название поставщика')),
                ('supplier_id', models.IntegerField(blank=True, null=True, verbose_name='id поставщика')),
            ],
            options={
                'verbose_name': 'Название компании',
                'verbose_name_plural': 'Названия компаний',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='название поставщика')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='задолженность')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('customer', models.IntegerField(verbose_name='заказчик')),
            ],
            options={
                'verbose_name': 'поставщик',
                'verbose_name_plural': 'поставщики',
            },
        ),
    ]
